# Generated by Django 4.1.7 on 2023-04-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='pw',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
